name: compile site

on:
    push:
        branches:
            - master


jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: setup go
              uses: actions/setup-go@v4
              with:
                go-version: 1.24.2
            
            - name: install deps
              run: go get .
            
            - name: build site
              run: go run main.go
    
    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
          - name: Setup Pages
            uses: actions/configure-pages@v5

          - name: Upload artifact
            uses: actions/upload-pages-artifact@v3
            with:
              # Upload static/ folder
              path: 'static'
              
          - name: Deploy to GH Pages
            id: deployment
            uses: actions/deploy-pages@v4